---
- name: Fixing SSH Weak Key Exchange Algorithms, Cipher Block Chaining (CBC), and MACs Enabled
  hosts: cmstest
  serial: 7
  become: true
  tasks:
  - name: Removing multiple strings from policy files
    lineinfile:
      path: "{{ item.path }}"
      regexp: "{{ item.value }}"
      state: absent
      mode: 0400
      backup: yes
    with_items:
      - { path: '/usr/share/crypto-policies/DEFAULT/libssh.txt', value: 'aes128-cbc', 'aes256-cbc', 'diffie-hellman-group-exchange-sha1', 'diffie-hellman-group1-sha1', 'gss-gex-sha1', 'gss-group1-sha1', 'gss-group14-sha1', 'rsa1024-sha1' }
      - { path: '/usr/share/crypto-policies/DEFAULT/nss.txt', value: 'aes128-cbc', 'aes256-cbc', 'diffie-hellman-group-exchange-sha1', 'diffie-hellman-group1-sha1', 'gss-gex-sha1', 'gss-group1-sha1', 'gss-group14-sha1', 'rsa1024-sha1' }
      - { path: '/usr/share/crypto-policies/DEFAULT/openssh.txt', value: 'aes128-cbc', 'aes256-cbc', 'diffie-hellman-group-exchange-sha1', 'diffie-hellman-group1-sha1', 'gss-gex-sha1', 'gss-group1-sha1', 'gss-group14-sha1', 'rsa1024-sha1' }
      - { path: '/usr/share/crypto-policies/DEFAULT/opensshserver.txt', value: 'aes128-cbc', 'aes256-cbc', 'diffie-hellman-group-exchange-sha1', 'diffie-hellman-group1-sha1', 'gss-gex-sha1', 'gss-group1-sha1', 'gss-group14-sha1', 'rsa1024-sha1' }
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"
  - name: backup files
    shell:  cp /etc/ssh/sshd_config /etc/ssh/sshd_config-{{ ansible_date_time.date}}

  # Do some housekeeping and remove any existing SSH cipher, kexalgorithm, and MAC entries
  - name: Removing old KexAlgorithms entry from the sshd configuration file
    lineinfile:
      path: /etc/ssh/sshd_config
      state: absent
      regexp: '^KexAlgorithms'

  - name: Removing old Ciphers entry from the sshd configuration file
    lineinfile:
      path: /etc/ssh/sshd_config
      state: absent
      regexp: '^Ciphers'

  - name: Removing old MACs entry from the sshd configuration file
    lineinfile:
      path: /etc/ssh/sshd_config
      state: absent
      regexp: '^MACs'

  # Add the new entries to the end of the sshd_config file
  - name: Adding new SSH Ciphers entry to the [sshd_config] file
    shell: echo "Ciphers aes128-ctr,aes192-ctr,aes256-ctr" >> /etc/ssh/sshd_config

  - name: Adding new SSH KexAlgorithms entry to the [sshd_config] file
    shell: echo "KexAlgorithms ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256" >> /etc/ssh/sshd_config

  - name: Adding new SSH MACs entry to the [sshd_config] file
    shell: echo "MACs hmac-sha2-256,hmac-sha2-512" >> /etc/ssh/sshd_config
  - name: Changing write permission
    shell: chmod  0600 /etc/ssh/sshd_config
  # Restart SSH Service
  - name: Restarting sshd.service on {{ ansible_fqdn }}
    service:
      name: sshd
      state: restarted
